[versions]
androidx-runtime = "1.10.2"
agp = "9.0.0"
arcore = "1.0.0-alpha10"
compose = "1.0.0-alpha10"
extensionsXr = "1.2.0"
scenecore = "1.0.0-alpha11"
kotlinxCoroutinesGuava = "1.10.2"
kotlin = "2.3.0"
concurrentFuturesKtx = "1.3.0"
activityCompose = "1.12.2"
composeBom = "2026.01.00"
material = "1.13.0"
adaptiveAndroid = "1.2.0"

[libraries]
androidx-arcore = { module = "androidx.xr.arcore:arcore", version.ref = "arcore" }
androidx-compose = { module = "androidx.xr.compose:compose", version.ref = "compose" }
androidx-scenecore = { module = "androidx.xr.scenecore:scenecore", version.ref = "scenecore" }
androidx-extensions-xr = { module = "com.android.extensions.xr:extensions-xr", version.ref = "extensionsXr" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "kotlinxCoroutinesGuava" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-concurrent-futures = { module = "androidx.concurrent:concurrent-futures-ktx", version.ref = "concurrentFuturesKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-runtime" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-adaptive-android = { group = "androidx.compose.material3.adaptive", name = "adaptive-android", version.ref = "adaptiveAndroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
